# Generated by Django 5.2.7 on 2025-12-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
