# Generated by Django 5.2.7 on 2026-01-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_orderdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='temp123', max_length=255),
            preserve_default=False,
        ),
    ]
